In [1]:
import cv2

In [7]:
def main():
    imgpath = "F:\\Tutorilas and Codes\\Image Processing\\standard_test_images\\lena_color_256.tif"
    img = cv2.imread(imgpath)
    
    print(type(img)) #Output - <class 'nupy.ndarray'> , ndarray - N dimensional array.
    
    print(img.dtype) #Output - uint8. Unsigned Integers of 8 bits.
    
    print(img.shape) #resolution #Output (512, 512, 3) #3 is the number of channels (eg. Blue, Green, Red)
    
    print(img.ndim) #no of dimensions. (height, width, n of channels)
                    # In case of greyscale or black & white image we have two dimensions namely height and width)
    
    print(img.size) # height*width*no of channels
    
    print(img)
    

In [8]:
if __name__ == "__main__":
    main()

<class 'numpy.ndarray'>
uint8
(256, 256, 3)
3
196608
[[[125 137 226]
  [130 136 223]
  [118 133 226]
  ...
  [127 145 230]
  [122 148 232]
  [100 114 210]]

 [[125 137 226]
  [130 136 223]
  [118 133 226]
  ...
  [127 145 230]
  [122 148 232]
  [100 114 210]]

 [[124 138 226]
  [121 133 223]
  [117 134 226]
  ...
  [118 133 222]
  [108 125 217]
  [ 90  87 182]]

 ...

 [[ 61  28  90]
  [ 61  28  91]
  [ 63  29  97]
  ...
  [ 71  53 140]
  [ 73  62 158]
  [ 74  59 161]]

 [[ 60  20  85]
  [ 59  25  91]
  [ 62  26  94]
  ...
  [ 82  64 153]
  [ 81  69 172]
  [ 78  65 170]]

 [[ 57  22  82]
  [ 62  30  94]
  [ 61  25  95]
  ...
  [ 84  71 167]
  [ 78  68 178]
  [ 81  72 183]]]
